/**
 * Pets SVG sanitization — defense-in-depth for the Pets rendering pipeline.
 *
 * This sanitizer is SEPARATE from sanitizeSvg.ts (used for untrusted user SVGs).
 * The two sanitizers have different threat models and MUST NOT share configuration:
 *
 * - sanitizeSvg.ts: For untrusted user content (stickers, drawings). Very strict.
 * - sanitizePetsSvg.ts: For Pets pipeline output. Broader allowlist for gradients,
 *   clipping/masking, text, and data-* attributes, but SMIL animations and CSS
 *   are stripped to keep the allowlist no broader than necessary.
 *
 * The Pets visual pipeline (customizers, eye-animation, emotions) performs
 * extensive string manipulation on SVG markup before injecting it via
 * `dangerouslySetInnerHTML`. While user inputs are validated at the parsing
 * boundary (normalizeHexColor, instanceId sanitization), this sanitizer acts
 * as a safety net at the *output* boundary.
 *
 * IMPORTANT: This file uses its own isolated DOMPurify instance to avoid
 * polluting the global DOMPurify used by other sanitizers.
 *
 * Blocked: <script>, <foreignObject>, <iframe>, <embed>, <object>, <a>,
 *          <use>, <image>, all event handlers (on*), href/xlink:href,
 *          SMIL animations (<animate*>), <style> tags and inline style.
 */

import DOMPurify from 'dompurify';

// ─────────────────────────────────────────────────────────────────────────────
// ISOLATED DOMPURIFY INSTANCE
// ─────────────────────────────────────────────────────────────────────────────
// We create a separate DOMPurify instance for Pets SVGs to avoid polluting
// the global DOMPurify with Pets-specific hooks. This ensures that:
// 1. The generic sanitizeSvg() remains strict and unaffected
// 2. Pets-specific data-* attribute handling doesn't leak to other sanitizers
// ─────────────────────────────────────────────────────────────────────────────

const petsPurify = DOMPurify();

/**
 * Hook to allow data-* attributes for the eye animation system.
 *
 * When ALLOWED_ATTR is specified, DOMPurify switches to strict whitelist mode
 * and would strip all attributes not in the list. The eye animation system
 * uses data-* attributes for storing geometry/state:
 *
 * - data-cx, data-cy: Eye center coordinates
 * - data-eye-top, data-eye-bottom: Eye bounds for clip-path animation
 * - data-clip-height: Full height of clip rect
 * - data-clip-id: Reference to the clipPath element ID
 *
 * These are generated by our own code (eye-animation.ts), not user input.
 *
 * SECURITY NOTE: data-* attributes cannot execute JavaScript directly.
 * They are inert storage and only become active if JavaScript explicitly
 * reads and acts on them. Our eye animation code only reads numeric values
 * and element IDs from these attributes.
 */
petsPurify.addHook('uponSanitizeAttribute', (_node, data) => {
  if (data.attrName.startsWith('data-')) {
    data.allowedAttributes[data.attrName] = true;
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ALLOWED TAGS
// ─────────────────────────────────────────────────────────────────────────────
// These are SVG elements that the Pets pipeline legitimately produces.
// Each category is documented with its use case.
// ─────────────────────────────────────────────────────────────────────────────

const PETS_ALLOWED_TAGS = [
  // Structural elements - basic SVG building blocks
  'svg',
  'g',
  'defs',
  'path',
  'circle',
  'ellipse',
  'rect',
  'line',
  'polyline',
  'polygon',

  // Gradient elements - used for body colors, eye shading, tear drops
  'radialGradient',
  'linearGradient',
  'stop',

  // Clipping and masking - used for eye blink animation
  'clipPath',
  'mask',

  // Text elements - used for sleepy "Zzz" animation
  'text',
  'tspan',
];

// ─────────────────────────────────────────────────────────────────────────────
// ALLOWED ATTRIBUTES
// ─────────────────────────────────────────────────────────────────────────────
// Attributes that the Pets pipeline uses. Grouped by category.
// ─────────────────────────────────────────────────────────────────────────────

const PETS_ALLOWED_ATTRS = [
  // Structural attributes
  'xmlns',
  'viewBox',
  'preserveAspectRatio',
  'width',
  'height',
  'id',
  'class',

  // Presentation attributes - colors, strokes, opacity
  'fill',
  'stroke',
  'stroke-width',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-dasharray',
  'stroke-dashoffset',
  'stroke-opacity',
  'fill-opacity',
  'fill-rule',
  'opacity',

  // Transform attributes - used for eye tracking, dizzy rotation
  'transform',

  // Clipping and masking references
  'clip-path',
  'clip-rule',
  'mask',

  // Geometry attributes for shapes
  'cx',
  'cy',
  'r',
  'rx',
  'ry',
  'x',
  'y',
  'x1',
  'y1',
  'x2',
  'y2',
  'd',
  'points',

  // Gradient attributes
  'offset',
  'stop-color',
  'stop-opacity',
  'gradientUnits',
  'gradientTransform',
  'patternUnits',
  'spreadMethod',
  'fx',
  'fy',

  // Text attributes - for sleepy "Zzz" text
  'text-anchor',
  'dominant-baseline',
  'font-family',
  'font-size',
  'font-weight',
];

// ─────────────────────────────────────────────────────────────────────────────
// FORBIDDEN TAGS
// ─────────────────────────────────────────────────────────────────────────────
// Elements that are explicitly blocked even if they appear in the input.
// ─────────────────────────────────────────────────────────────────────────────

const PETS_FORBIDDEN_TAGS = [
  'script',        // JavaScript execution
  'foreignObject', // Can embed arbitrary HTML/CSS
  'iframe',        // Can load external content
  'embed',         // Can load external content
  'object',        // Can load external content
  'use',           // Can reference external SVG content
  'image',         // Can load external images (disabled for Pets)
  'a',             // Links (not needed, could be used for phishing)
];

// ─────────────────────────────────────────────────────────────────────────────
// FORBIDDEN ATTRIBUTES
// ─────────────────────────────────────────────────────────────────────────────
// Attributes that are explicitly blocked to prevent XSS.
// ─────────────────────────────────────────────────────────────────────────────

const PETS_FORBIDDEN_ATTRS = [
  // DOM Event handlers - comprehensive list
  // Any of these could execute arbitrary JavaScript
  'onload',
  'onerror',
  'onclick',
  'ondblclick',
  'onmousedown',
  'onmouseup',
  'onmouseover',
  'onmouseout',
  'onmouseenter',
  'onmouseleave',
  'onmousemove',
  'onfocus',
  'onblur',
  'onkeydown',
  'onkeyup',
  'onkeypress',
  'onchange',
  'oninput',
  'onsubmit',
  'onreset',
  'onscroll',
  'onwheel',
  'oncopy',
  'oncut',
  'onpaste',
  'ondrag',
  'ondragend',
  'ondragenter',
  'ondragleave',
  'ondragover',
  'ondragstart',
  'ondrop',

  // CSS Animation/Transition events
  'onanimationend',
  'onanimationstart',
  'onanimationiteration',
  'ontransitionend',
  'ontransitionstart',
  'ontransitioncancel',

  // SVG SMIL events - can trigger JavaScript
  'onbegin',
  'onend',
  'onrepeat',

  // Touch events
  'ontouchstart',
  'ontouchend',
  'ontouchmove',
  'ontouchcancel',

  // Link attributes - Pets uses url(#id) for internal refs, not href
  'href',
  'xlink:href',
];

// ─────────────────────────────────────────────────────────────────────────────
// CONFIGURATION
// ─────────────────────────────────────────────────────────────────────────────

/** Maximum SVG string length (512 KB). Pets SVGs with all emotion overlays are ~30 KB. */
const MAX_SVG_LENGTH = 512 * 1024;

/**
 * Convert inline styles on `<stop>` elements into presentation attributes.
 *
 * Several pipeline assets (the generic baby/adult SVG data, the SVG
 * customizers, renderer fallbacks) declare gradient stops as
 * `<stop offset="0%" style="stop-color:#8b5cf6;stop-opacity:1" />`.
 * This sanitizer strips inline CSS by design — which silently discarded the
 * stop colors, and SVG's default stop-color is BLACK, so every gradient in
 * those assets rendered as a solid black blob (the "black muppet" baby).
 * Rewriting the two stop properties into the allowed `stop-color` /
 * `stop-opacity` presentation attributes carries the colors through
 * sanitization. Runs BEFORE DOMPurify; only those two properties are lifted,
 * and quotes/brackets are stripped from values so no attribute injection is
 * possible (the input is our own pipeline output, not user content).
 */
function normalizeStopStyles(svg: string): string {
  return svg.replace(/<stop\b[^>]*>/g, (tag) => {
    const styleMatch = tag.match(/\sstyle="([^"]*)"/);
    if (!styleMatch) return tag;
    const attrs: string[] = [];
    for (const decl of styleMatch[1].split(';')) {
      const idx = decl.indexOf(':');
      if (idx === -1) continue;
      const prop = decl.slice(0, idx).trim();
      const value = decl.slice(idx + 1).trim().replace(/["'\\<>]/g, '');
      if ((prop === 'stop-color' || prop === 'stop-opacity') && value) {
        attrs.push(`${prop}="${value}"`);
      }
    }
    let out = tag.replace(styleMatch[0], '');
    if (attrs.length > 0) {
      out = out.replace(/\s*(\/?)>$/, (_end, slash: string) => ` ${attrs.join(' ')}${slash ? ' /' : ''}>`);
    }
    return out;
  });
}

/**
 * Inline the pipeline's CSS custom properties before DOMPurify strips them.
 *
 * The ₿AO generator and the Open Design adult forms (via
 * applyCssVariableColors) declare their palette as a
 * `<style>:root{--baseColor:…;--secondaryColor:…;--eyeColor:…}</style>` block
 * and reference it with `var(--baseColor)` / `var(--baseColor, #fallback)`.
 * This sanitizer strips `<style>` tags by design — so every var() lost its
 * definition: ₿AO bodies (no fallback) rendered BLACK, and Open Design forms
 * silently fell back to their baked-in hex instead of the pet's colors.
 * Substituting the declared values (fallback honored when undeclared) carries
 * the real palette through sanitization. Runs BEFORE DOMPurify; values are
 * restricted to color-ish characters so no CSS/attribute injection is
 * possible (the input is our own pipeline output, not user content).
 */
function inlineCssVariables(svg: string): string {
  const styleBlocks = svg.match(/<style\b[^>]*>[\s\S]*?<\/style>/gi);
  if (!styleBlocks) return svg;

  const vars = new Map<string, string>();
  for (const block of styleBlocks) {
    const declRe = /(--[a-zA-Z][\w-]*)\s*:\s*([^;{}]+)\s*;/g;
    let m: RegExpExecArray | null;
    while ((m = declRe.exec(block)) !== null) {
      const name = m[1];
      const value = m[2].trim();
      // Only accept color-ish tokens (hex, rgb()/hsl(), named colors, %).
      if (/^[#a-zA-Z0-9.,%() -]+$/.test(value)) {
        vars.set(name, value);
      }
    }
  }

  // Substitute var(--name) and var(--name, fallback); keep the fallback when
  // the variable was not declared (e.g. a style block we couldn't parse).
  const substituted = svg.replace(
    /var\(\s*(--[a-zA-Z][\w-]*)\s*(?:,\s*([^)]*?)\s*)?\)/g,
    (whole, name: string, fallback?: string) => {
      const value = vars.get(name);
      if (value) return value;
      if (fallback && /^[#a-zA-Z0-9.,%() -]+$/.test(fallback.trim())) return fallback.trim();
      return whole;
    },
  );

  // The definitions are inlined now — drop the style blocks entirely.
  return substituted.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, '');
}

// ─────────────────────────────────────────────────────────────────────────────
// SANITIZER FUNCTION
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Sanitize a Pets SVG string before injection via `dangerouslySetInnerHTML`.
 *
 * This is the output-boundary safety net for the Pets rendering pipeline.
 * It strips scripts, event handlers, SMIL animations, inline CSS, and other
 * dangerous constructs while preserving the gradients, clip paths, and basic
 * shapes that the pipeline legitimately produces.
 *
 * ISOLATION: Uses a dedicated DOMPurify instance (petsPurify) to avoid
 * affecting the global DOMPurify used by sanitizeSvg.ts.
 *
 * Key features:
 * - All data-* attributes are allowed (via isolated hook)
 * - SMIL animation elements and attributes are stripped
 * - Inline style attributes and <style> tags are stripped
 * - Event handlers and href attributes are blocked
 *
 * What this sanitizer catches:
 * - Any <script> tags that might be injected
 * - Event handlers like onclick, onload, etc.
 * - SMIL animations (<animate>, <animateTransform>, <animateMotion>)
 * - Inline style attributes and <style> tags
 * - Links via href/xlink:href
 * - Dangerous elements like foreignObject, iframe, etc.
 */
export function sanitizePetsSvg(dirty: string): string {
  if (dirty.length > MAX_SVG_LENGTH) {
    if (import.meta.env.DEV) {
      console.warn('[sanitizePetsSvg] SVG exceeds max length, rejecting');
    }
    return '';
  }

  // Use the isolated petsPurify instance, NOT the global DOMPurify
  // We do NOT use USE_PROFILES because the SVG profile has its own
  // internal whitelist that conflicts with our explicit ALLOWED_TAGS/ALLOWED_ATTR.
  // normalizeStopStyles lifts <stop> inline styles into allowed presentation
  // attributes first — otherwise the style stripping would black out every
  // gradient that declares its colors via style="stop-color:…".
  // inlineCssVariables substitutes the pipeline's :root palette variables —
  // otherwise stripping <style> would black out every var(--baseColor) fill
  // (₿AO bodies) or downgrade Open Design forms to their fallback hexes.
  return petsPurify.sanitize(inlineCssVariables(normalizeStopStyles(dirty)), {
    ALLOWED_TAGS: PETS_ALLOWED_TAGS,
    ALLOWED_ATTR: PETS_ALLOWED_ATTRS,
    FORBID_TAGS: PETS_FORBIDDEN_TAGS,
    FORBID_ATTR: PETS_FORBIDDEN_ATTRS,
    RETURN_DOM: false,
    RETURN_DOM_FRAGMENT: false,
  }) as string;
}

// ─────────────────────────────────────────────────────────────────────────────
// DIFFERENCES FROM GENERIC sanitizeSvg()
// ─────────────────────────────────────────────────────────────────────────────
//
// Tags that Pets allows but generic does NOT:
// - defs, radialGradient, linearGradient, stop (gradients)
// - clipPath, mask (clipping/masking)
// - text, tspan (text rendering)
//
// Attributes that Pets allows but generic does NOT:
// - id, class (element identification)
// - preserveAspectRatio
// - clip-path, clip-rule, mask (clipping references)
// - fill-rule
// - All gradient attributes (offset, stop-color, stop-opacity, etc.)
// - Text attributes (font-family, font-size, etc.)
// - data-* attributes (via hook) ← NOT allowed in generic
//
// Previously allowed (now removed to match base sanitizer posture):
// - SMIL animation elements: animate, animateTransform, animateMotion
// - <style> tags and inline style attributes
// - transform-origin, transform-box
// - SMIL animation attributes (attributeName, values, dur, etc.)
//
// The generic sanitizer is intentionally stricter because it handles
// untrusted user content (stickers, drawings), while Pets handles
// content generated by our own pipeline with validated inputs.
// ─────────────────────────────────────────────────────────────────────────────
